- frontend/src/components/FAB/index.stories.tsx
- frontend/src/components/FAB/index.styles.ts
- frontend/src/components/FAB/index.tsx
> feat: FAB 컴포넌트 UI 구현

- frontend/src/components/Snackbar/index.stories.tsx
- frontend/src/components/Snackbar/index.styles.ts
- frontend/src/components/Snackbar/index.tsx
- frontend/src/style.d.ts
- frontend/src/style/theme.ts
- Snackbar 컴포넌트 UI 구현
close #11
> feat: Snackbar 컴포넌트 UI 구현

- frontend/src/components/Snackbar/index.styles.ts
- frontend/src/components/Snackbar/index.tsx
- frontend/src/context/Snackbar.tsx
- frontend/src/index.html
- frontend/src/index.tsx
- snackbar를 최상위에서 보여주는 기능
close #16
> feat: Snackbar 컴포넌트 기능 구현

- frontend/src/App.tsx
- frontend/src/components/@styled/Layout/index.tsx
- frontend/src/components/Header/index.styles.ts
- frontend/src/pages/CreatePostPage/index.styles.ts
- frontend/src/pages/CreatePostPage/index.tsx
- frontend/src/style/GlobalStyle.tsx
> feat: CreatePostPage 구현

- frontend/.storybook/main.js
- frontend/.storybook/preview.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Spinner/index.stories.tsx
- frontend/src/components/Spinner/index.styles.ts
- frontend/src/components/Spinner/index.tsx
- frontend/src/dummy.ts
- frontend/src/index.tsx
- frontend/src/pages/PostPage/index.stories.tsx
- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
- 상세 Post 페이지에서 id를 params로 받아 MSW에서 모킹한 API와 연결
close #35
> feat: PostPage Mocking API 연결

- frontend/src/pages/CreatePostPage/index.styles.ts
- frontend/src/pages/CreatePostPage/index.tsx
- 글작성 페이지를 API와 연동한다.
close #36
> feat: CreatePostPage Api 연동

- frontend/src/pages/CreatePostPage/index.tsx
- postPage에서 글 등록 시 MainPage의 글목록 가져오기 로직 캐시를 초기화한다.
#39
> feat: Mutate 발생시 getByPage 캐시 업데이트 

- frontend/src/components/Spinner/index.styles.ts
- frontend/src/mocks/handlers/posts/index.ts
- frontend/src/pages/CreatePostPage/index.styles.ts
- frontend/src/pages/CreatePostPage/index.tsx
- frontend/src/pages/MainPage/index.tsx
- frontend/src/style.d.ts
- frontend/src/style/theme.ts
> feat: createPostPage Validation 로직 추가

- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
- URL로 존재하지 않는 글에 대한 접근을 한 경우 에러 메시지를 보여준다.
close #45
> feat: 없는 글 조회시 에러 메시지 렌더링

- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/components/Header/index.stories.tsx
- frontend/src/components/Header/index.styles.ts
- frontend/src/components/Header/index.tsx
- frontend/src/components/PostListItem/index.tsx
- frontend/src/components/Snackbar/index.tsx
- frontend/src/components/Spinner/index.stories.tsx
- frontend/src/components/Spinner/index.tsx
- frontend/src/index.tsx
- frontend/src/mocks/handlers/posts/index.ts
- frontend/src/mocks/worker.ts
- frontend/src/pages/CreatePostPage/index.stories.tsx
- frontend/src/pages/CreatePostPage/index.tsx
- frontend/src/pages/MainPage/index.stories.tsx
- frontend/src/pages/MainPage/index.tsx
- frontend/src/pages/NotFoundPage/index.stories.tsx
- frontend/src/pages/NotFoundPage/index.styles.ts
- frontend/src/pages/NotFoundPage/index.tsx
- frontend/src/pages/PostPage/index.stories.tsx
- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
- frontend/src/style/GlobalStyle.tsx
모듈을 import 하는 부분을 카테고리에 따라 정렬한다.
close #52
> refactor: import 순서 정렬

- backend/sokdak/src/main/java/com/wooteco/sokdak/post/controller/PostController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostUpdateRequest.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
> feat: 게시글 수정, 삭제 기능 구현

- frontend/src/mocks/handlers/posts/index.ts
MSW mocking 코드에 디테일을 추가한다.
close #64
> feat: 새 게시물이 최상단에 위치하도록 MSW 코드 수정

- frontend/src/App.tsx
- frontend/src/components/Header/index.tsx
- frontend/src/constants/path.ts
- frontend/src/constants/snackbar.ts
- frontend/src/hooks/queries/post/useCreatePost.ts
- frontend/src/pages/CreatePostPage/index.tsx
- frontend/src/pages/MainPage/index.tsx
- frontend/src/pages/NotFoundPage/index.tsx
- frontend/src/pages/PostPage/index.tsx
> refactor: 변수명 정리및 상수화

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/Encryptor.java
> refactor: Encryptor static 제거

- backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/EmailServiceTest.java
- 사용자에게 이메일 발송 기능 검증
- 인증 코드 저장 기능 검증
> refactor: EmailService 테스트 코드 작성

- frontend/src/assets/images/heart.svg
좋아요를 위해 heart.svg 추가
```jsx
import Heart from '@/assets/images/heart.svg';
...
<Heart fill="" stroke="" />
// 사용
```
close #97
> feat: 좋아요를 위해 heart.svg 추가

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthCodeGenerator.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/config/WebMvcConfig.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/service/EmailService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/Login.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/LoginArgumentResolver.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/EmailServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/repository/PostRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/ControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
> feat: 게시글 회원 연관관계 매핑

- frontend/webpack/webpack.prod.js
> chore: production용 webpack 설정

- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java
add 되지 않아서 commit 되지 않았던 파일 추가
> Fix : adding unversioned file

- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/controller/CommentController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Message.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/CommentResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/CommentsResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/NewCommentRequest.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/exception/InvalidMessageException.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/repository/MemberRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/service/MemberService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/util/RandomNicknameGenerator.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/controller/CommentControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/MessageTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/repository/CommentRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/repository/MemberRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/ControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
> feat: 댓글 기능 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/like/controller/LikeController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/domain/Like.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/dto/LikeFlipResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/LikeRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/LikeAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/controller/LikeControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/service/LikeServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/ControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/HttpMethodFixture.java
> feat: 좋아요 등록/취소 기능 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsElementResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/repository/CommentRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/controller/LikeControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/repository/MemberRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/repository/PostRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
- 게시글 댓글 연관관계 매핑
- 게시글 댓글 양방향 연관 관계 매핑
- 테스트 검증 요소 미비
> feat: 게시글 댓글 연관관계 매핑

- frontend/src/components/LikeButton/index.stories.tsx
- frontend/src/components/LikeButton/index.styles.ts
- frontend/src/components/LikeButton/index.tsx
- frontend/src/dummy.ts
- frontend/src/hooks/queries/likes/useLike.ts
- frontend/src/mocks/handlers/posts/index.ts
- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
- frontend/src/types/post.d.ts
> feat: 게시물 좋아요 기능 구현

- frontend/src/dummy.ts
- frontend/src/mocks/handlers/posts/index.ts
- frontend/src/pages/PostPage/index.tsx
- frontend/src/types/post.d.ts
자신의 게시물일 경우만 수정, 삭제 버튼을 표시한다.
close #132
> feat: 자신의 게시물일 경우만 수정, 삭제 버튼 표시

- frontend/package.json
- frontend/src/components/PostListItem/index.styles.ts
- frontend/src/context/Auth.tsx
- frontend/src/hooks/queries/member/useLogin.ts
- frontend/src/pages/LoginPage/index.tsx
- frontend/src/pages/PostPage/components/CommentInput/index.tsx
- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
- frontend/src/pages/SignUpPage/components/EmailInput/index.tsx
- frontend/src/pages/SignUpPage/components/NicknameInput/index.tsx
- frontend/src/utils/regExp.ts
> feat: fe 토큰 로그인으로 변경

- backend/sokdak/src/main/java/com/wooteco/sokdak/config/AsyncConfig.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/service/EmailSenderImpl.java
이메일 발송을 비동기로 전
- 비동기 쓰레드 풀 설정
- @Async 어노테이션을 이용한 이메일 발송 비동기화
실제 비동기 적용후 사용자 입장에서 대기 시간이 4000~3500ms에서 200ms ~ 10ms까지 줄었습니다.
> feat: 이메일 발송 비동기 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/controller/CommentController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/exception/CommentNotFoundException.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/controller/PostController.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/acceptance/CommentAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/controller/CommentControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/util/CommentFixture.java
> feat: 댓글 삭제 기능 구현 #168

- Jenkinsfile
multi branch pipeline을 위한 Jenkinsfile 추가
> feat: Jenkinsfile 추가

- backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/dto/HashtagsSearchRequest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/acceptance/HashtagAcceptanceTest.java
> test: 인수테스트 추가 및 Dto @NotBlank 어노테이션 제거

- backend/sokdak/build.gradle
- backend/sokdak/src/main/java/com/wooteco/sokdak/config/JasyptConfig.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/resources/application-dev.yml
- backend/sokdak/src/main/resources/application-local.yml
- backend/sokdak/src/main/resources/application.yml
yml 파일의 속성들을 암호화했다.
jasypt 라이브러리 사용
dev 서버에서는 jasypt의 password를 환경변수로 설정해주어야 한다.
> feat: yml 속성값 암호화

- backend/sokdak/src/main/java/com/wooteco/sokdak/config/WebMvcConfig.java
> fix: cors 허용 도메인 추가

- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/acceptance/CommentAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/controller/CommentControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/CommentReportAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/PostReportAcceptanceTest.java
- backend/sokdak/src/test/resources/truncate.sql
> fix: 테스트 실패 해결

- backend/sokdak/src/main/resources/logback/file-logger.xml
로그 파일 저장 경로를 /home/ubuntu/logfiles 로 수정
> chore: 로그파일 저장 경로 수정

- Jenkinsfile
- frontend/package.json
> feat: Jenkinsfile 작성

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/dto/AuthInfo.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/RoleType.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/token/AuthenticationPrincipalArgumentResolver.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/token/JwtTokenProvider.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/token/TokenManager.java
- backend/sokdak/src/main/resources/import.sql
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/controller/AuthControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/service/CommentReportServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/service/PostReportServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/support/token/JwtTokenProviderTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
- backend/sokdak/src/test/resources/truncate.sql
> feat: 토큰에 닉네임/역할 정보 추가

- backend/sokdak/src/test/resources/application.yml
test코드에서 yml파일 속성값을 읽어오지 못하는 문제 수정
> fix: test코드에서 yml파일 속성값을 읽어오지 못하는 문제 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/board/dto/BoardContentElement.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/board/dto/BoardContentPostElement.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/board/acceptance/BoardAcceptanceTest.java
메인페이지 조회 API 수정
메인페이지 조회 시 게시글 id 속성 추가
resolve #247
> feat: 메인페이지 조회 API 수정

- jenkins/Jenkinsfile
> fix: 파이프라인 stages 하나로 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/controller/CommentController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/CommentResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/controller/CommentControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
특정 게시글의 댓글 목록 조회시, response에 댓글 작성자인지 알려주는 필드 추가
> feat: 특정 게시글의 댓글 목록 조회시, response에 댓글 작성자인지 알려주는 필드 추가

- jenkins/Jenkinsfile
> chore: test for Jenkinsfile

- backend/sokdak/src/main/java/com/wooteco/sokdak/support/token/AuthorizationExtractor.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/token/JwtTokenProvider.java
refresh token을 통해 로그아웃 및 자동로그인 기능 구현
access token이 만료됐을 시 argument resolver에서 토큰 검증을 처리할 때 만료되었으면 라이브러리 단에서 예외를 터뜨려 만료된 토큰의 정보를 빼오지 못하는 이슈가 있었습니다.
이를 예외 처리를 통해 만료된 토큰이더라도 객체를 빼올수 있도록 했습니다.
> feat: JWT 로그아웃 및 자동로그인 구현

- frontend/src/assets/images/chevron-down.svg
- frontend/src/components/@shared/Dropdown/index.stories.tsx
- frontend/src/components/@shared/Dropdown/index.styles.ts
- frontend/src/components/@shared/Dropdown/index.tsx
- frontend/src/constants/queries.ts
- frontend/src/dummy.ts
- frontend/src/hooks/queries/board/useBoards.ts
- frontend/src/mocks/handlers/posts/index.ts
- frontend/src/pages/BoardPage/components/BoardCategory/index.styles.ts
- frontend/src/pages/BoardPage/components/BoardCategory/index.tsx
- frontend/src/pages/BoardPage/index.tsx
- frontend/src/types/boards.d.ts
- 상세 게시판 화면 내에서 드롭다운을 통해 카테고리를 선택하는 기능을 구현한다.
close #282
> feat: 상세 게시판 화면내에서 카테고리 분류 

- backend/sokdak/build.gradle
- backend/sokdak/src/main/resources/logback-access.xml
- backend/sokdak/src/main/resources/logback-spring.xml
- backend/sokdak/src/main/resources/logback/console-access-logger.xml
- backend/sokdak/src/main/resources/logback/file-access-logger.xml
- backend/sokdak/src/main/resources/logback/file-logger.xml
- backend/sokdak/src/main/resources/logback/slack-logger.xml
> feat: 서버에서의 에러 로그를 슬랙으로 전송하는 기능 구현

- backend/sokdak/build.gradle
- backend/sokdak/src/main/resources/logback/file-access-logger.xml
- backend/sokdak/src/main/resources/logback/file-logger.xml
1. 중복되는 의존성 제거
2. 파일 저장 경로를 운영/개발 서버에 맞는 경로로 수정
> fix: 중복되는 의존성 삭제

- backend/sokdak/src/main/resources/import.sql
테스트용 계정 추가
헌치, 조시, 동키콩, 무비, 토르 계정 추가
> feat: 테스트용 계정 추가

- frontend/src/pages/PostPage/components/CommentInput/index.tsx
> feat: 댓글 작성시 익명/기명 선택 체크박스를 CheckBox 컴포넌트로 교체

- backend/sokdak/src/main/java/com/wooteco/sokdak/board/repository/PostBoardRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/exception/PostBoardNotFoundException.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
> feat: 글 상세보기 Dto에 게시판 id 추가

- frontend/src/components/Timer/index.stories.tsx
- frontend/src/components/Timer/index.styles.ts
- frontend/src/components/Timer/index.tsx
- frontend/src/pages/SignUpPage/components/EmailInput/index.styles.ts
- frontend/src/pages/SignUpPage/components/EmailInput/index.tsx
- frontend/src/pages/SignUpPage/index.styles.ts
이메일 인증 시간이 초과됐을 경우 예외 처리를 진행한다. 
close #297
> feat: 이메일 인증 시간 초과 예외 처리

- backend/sokdak/src/main/resources/import.sql
> feat: 테스트 계정 비밀번호 변경

- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Nickname.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/repository/MemberRepositoryTest.java
> feat: 회원 닉네임 유니크 제약 조건 추가

- frontend/package.json
- frontend/src/__test__/NotFound.test.tsx
- frontend/src/setupTests.ts
> fix: 회원가입 및 Notfound test 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/board/repository/PostBoardRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
인기글 조회 안되는 문제 해결
postBoard가 여러 개 조회되는 문제.
List로 받아서 get(0)하도록 응급처치
issue #341
> fix: 인기글 조회 안되는 문제 해결

- frontend/src/pages/MainPage/index.tsx
게시판 이름에 이모지를 표기한다. 
close #333
> fix: 게시판 이름에 이모지 표기

- frontend/package.json
- frontend/src/__test__/NotFound.test.tsx
- frontend/src/components/Header/index.styles.ts
- frontend/src/context/Auth.tsx
- frontend/src/hooks/queries/comment/useComments.ts
- frontend/src/index.tsx
- frontend/src/setupTests.ts
> fix:게시판 새로고침시 자신 글 수정삭제 안나오는 문제 및 댓글삭제문제 해결

- frontend/src/components/HashTag/index.styles.ts
해시태그 안 글씨가 정렬되지 않았던 문제 해결 
close #337
> fix: 해시태그 안 글씨 정렬

- backend/sokdak/src/main/resources/logback-spring.xml
- backend/sokdak/src/main/resources/logback/file-db-logger.xml
> refactor: dev 서버에서 sql로그를 기록하도록 변경

- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java
단건 조회 블라인드 안되는 버그 수정
Dto에 blocked 추가
> fix: 단건 조회 블라인드 안되는 버그 수정

- jenkins/Jenkinsfile
CI/CD 로직 순서 수정
BE와 FE가 TEST를 실행하고, BE와 FE가 빌드를 실행하고, BE와 FE의 배포가 실행되는 순서로 수정
> refactor: CI/CD 로직 순서 수정

- backend/sokdak/src/main/resources/application-dev.yml
- backend/sokdak/src/main/resources/application-local.yml
ddl-auto: none으로 설정안되있는거 none으로 변경
> fix: ddl-auto: none으로 설정안되있는거 none으로 변경

- backend/sokdak/src/main/resources/schema.sql
> chore: schema.sql 주석제거

- frontend/src/pages/PostPage/index.tsx
게시물이 없는 경우 안내메시지가 짤리는 경우를 해결한다. 
close #370
> fix: 게시물이 없는 경우 안내메시지 짤림 해결

- backend/sokdak/src/main/resources/logback-spring.xml
- backend/sokdak/src/main/resources/logback/slack-logger.xml
> refactor: 환경마다 root 로그 레벨 설정

- backend/sokdak/src/main/resources/logback-spring.xml
logback-spring.xml 파일의
ASYNC-SLACK-PROD -> ASYNC-SLACK-PROD-ERROR 로 수정
> fix: appender name 오타 수정

- frontend/src/assets/images/notification-icon.svg
- frontend/src/components/@shared/Dropdown/index.styles.ts
- frontend/src/components/Header/Notification/index.stories.tsx
- frontend/src/components/Header/Notification/index.styles.ts
- frontend/src/components/Header/Notification/index.tsx
- frontend/src/components/Header/index.stories.tsx
- frontend/src/components/Header/index.styles.ts
- frontend/src/components/Header/index.tsx
- frontend/src/constants/queries.ts
- frontend/src/hooks/queries/notification/useNotificationExists.ts
- frontend/src/mocks/handlers/members/index.ts
Header에 알람 아이콘을 표시한다.
- 30초마다 API 요청을 보내 알람의 여부를 확인한 후 알람이 있을 경우 표시해준다.
- 알람 버튼을 클릭할 경우 알람 페이지로 이동한다.
close #400
> feat: 헤더에 알람아이콘 표시

- frontend/src/pages/BoardPage/components/BoardCategory/index.styles.ts
> style: 게시판 선택 드롭다운 디자인 변경

- jenkins/dev/Jenkinsfile
dev Jenkinsfile 수정
FE BUILD stage에 npm run `bulid-prod`를 `bulid-dev`로 수정
resolve #425
> fix: dev Jenkinsfile 수정

- .github/workflows/backend2.yml
깃헙액션 테스트를 위한 임시 pr입니다. 나중에 삭제할 예정
> 깃헙액션 테스트를 위한 임시 pr입니다. 나중에 삭제할 예정

- backend/sokdak/src/main/java/com/wooteco/sokdak/tmp/TmpCodeForGIthubActions.java
> test: 깃헙액션 테스트를 위한 코드 추가 추후 삭제 예정

- .github/workflows/backend.yml
> chore: 백엔드 깃헙액션 스크립트 추가

- .github/workflows/frontend.yml
> chore: 프론트엔드 깃헙액션 스크립트 추가

- frontend/src/setupTests.ts
> fix: 프론트 테스트 깨지는거 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Nickname.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Password.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Username.java
> fix: 값객체에 equals & hashcode 추가 #420

- .github/workflows/backend.yml
> feat: GithubAction 자바 설치 스크립트 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/support/AuthInterceptor.java
interceptor 에서 토큰 검증 예외 던지던 로직을 boolean 값 반환으로 변경
401 응답을 보내지만, 예외 메시지를 던지지 않는다. 다른 방법 강구 필요
> fix: interceptor 에서 토큰 검증 예외 던지던 로직을 boolean 값 반환으로 변경

- backend/sokdak/.github/workflows/backend.yml
> chore: 백엔드 깃헙액션 스크립트 수정

- .github/workflows/backend.yml
> chore: 깃헙액션 백엔드 스크립트 수정

- .github/workflows/backend.yml
> feature: GithubAction 경로 수정

- .github/workflows/backend.yml
> feature: Dev 스크립트 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/tmp/TmpCodeForGIthubActions.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java
> 깃헙 액션 테스트를 위한 임시 pr, 저희dev, main브랜치에는 반영되지 않습니다.

- .github/workflows/backend.yml
> infra: 백엔드 깃헙액션 스크립트 수정

- jenkins/dev/Jenkinsfile
- jenkins/main/Jenkinsfile
> chore: 젠킨스 파일에 테스트 돌리는 코드 삭제

- backend/sokdak/src/docs/asciidoc/index.adoc
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/controller/NotificationController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/domain/Notification.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/dto/NotificationResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/dto/NotificationsResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NotificationRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/acceptance/NotificationAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/controller/NotificationControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/domain/NotificationTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/repository/NotificationRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
> feat: 알림 조회 기능 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/acceptance/NotificationAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
자신의 게시글에 댓글을 달아도 알림이 등록되지 않는 기능 구현
resolve #434
> feat: 자신의 게시글에 댓글을 달아도 알림이 등록되지 않는 기능 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/report/service/CommentReportService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/board/acceptance/BoardAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/acceptance/HashtagAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/LikeAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/acceptance/MemberAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/acceptance/NotificationAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/CommentReportAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/PostReportAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/DatabaseCleaner.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/CommentFixture.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/HttpMethodFixture.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
대댓글 알림 작성시 댓글 작성자에 대한 알림 등록 기능 구현
> feat: 대댓글 알림 작성시 댓글 작성자에 대한 알림 등록 기능 구현

- backend/sokdak/src/docs/asciidoc/index.adoc
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/controller/NotificationController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/domain/Notification.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/excpetion/NotificationNotFoundException.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/acceptance/NotificationAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/controller/NotificationControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/domain/NotificationTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
알림 삭제 기능 구현
커밋 메시지가 잘못되었네요. 댓글 삭제 기능이 아닌 알림 삭제 기능 입니다~
> feat: 알림 삭제 기능 구현

- backend/sokdak/.github/workflows/backend.yml
- backend/sokdak/build.gradle
> feat: 소나큐브 설정 등 기타작업을 위한 브랜치 입니다. # 467

- frontend/public/index.html
- frontend/src/hooks/queries/notification/useDeleteNotification.ts
- frontend/src/index.tsx
- frontend/src/jenniferFront.ts
- frontend/src/mocks/handlers/notifications/index.ts
- production 모드에서 프론트엔드 성능측정 모니터링을 위한 jennifer front 적용
close #464
> feat: frontend jennifer-front 적용

- README.md
> docs: README.md 멤버 소개 업데이트

- .github/workflows/backend.yml
- README.md
> chore: dev와 main conflict 해결

- .github/workflows/backend.yml
> feat: 백엔드 깃헙액션 스크립트에 소나큐브 관련 설정 추가

- .github/workflows/backend.yml
> feat: 깃헙액션에 소나큐브 스크립트 변경

- backend/sokdak/.github/workflows/backend.yml
> chore: 깃헙액션 소나큐브 관련 스크립트 변경

- .github/workflows/backend.yml
> feat: dev브랜치 깃헙액션 소나큐브 관련 스크립트 변경

- .github/workflows/backend.yml
> feat: 깃헙액션 소나큐브 스크립트 수정

- .github/workflows/backend.yml
> feat: dev 깃헙액션 소나큐브 스크립트 수정

- backend/sokdak/.github/workflows/backend.yml
- backend/sokdak/build.gradle
> feat: 소나큐브 관련 설정 추가

- README.md
> docs: readme.md api 링크 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/exception/AuthorizationException.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/exception/LoginFailedException.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/CommentResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/ReplyResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/domain/Notification.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/main/resources/static/index.html
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/controller/AuthControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/domain/NotificationTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java
로그인 실패시 401 응답으로 반환하도록 변경
closes #496
>  refactor: 로그인 실패시 401 응답으로 반환하도록 변경

- frontend/src/context/Auth.tsx
- frontend/src/index.tsx
> fix: 알림페이지에서 새로고침 시 이미 로그인한 유저입니다 스낵바 메시지 렌더링

- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/domain/Notification.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/acceptance/NotificationAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
알림 조회시, 조회 확인 필드를 true로 변경
resolve #484
> feat: 알림 조회시, 조회 확인 필드를 true로 변경

- frontend/src/pages/PostPage/components/PostContent/index.styles.ts
긴 문장이 개행되지 않는 문제 해결 
close #505
> fix: 긴 문장이 개행되지 않는 문제 해결

- frontend/src/pages/PostPage/components/CommentBox/index.styles.ts
- frontend/src/pages/PostPage/components/CommentBox/index.tsx
- frontend/src/pages/PostPage/components/CommentList/index.styles.ts
- frontend/src/pages/PostPage/components/CommentList/index.tsx
- frontend/src/pages/PostPage/components/ReplyForm/index.styles.ts
- frontend/src/pages/PostPage/components/ReplyForm/index.tsx
- 해상도에 따라 달라지는 것 같아 margin으로 해결한 코드를 삭제했습니다. 
close #499
> fix: 답글 관련 사소한 수정 

- .github/workflows/backend.yml
db시간과 깃헙액션시간 불일치 해결을 위해 깃헙액션 스크립트 timezone kst로 설정하는 코드 추가
resolve #514
> chore: 깃헙액션 스크립트 timezone kst로 설정하는 코드 추가

- .github/workflows/backend.yml
깃헙액션 스크립트에 타임존 kst로 설정하는 코드 추가
> chore: 깃헙액션 스크립트에 타임존 kst로 설정하는 코드 추가

- frontend/src/utils/decodeJwt.ts
한글닉네임 설정시 프로필 페이지에서 파싱 오류로 인한 불특정  문자 렌더링
close #521
> fix: 한글 닉네임 토큰 파싱 오류 해결

- backend/sokdak/build.gradle
- backend/sokdak/src/main/resources/application-dev.yml
> chore: spring actuator build.gradle, dev yml 파일 설정

- backend/sokdak/src/main/java/com/wooteco/sokdak/support/AuthInterceptor.java
> chore: get method 요청에 대해 인증 인터셉터 예외 추가

- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/report/service/CommentReportService.java
댓글 신고 n+1 개선
fetch join을 이용한 개선
> refactor: 댓글 신고 n+1 개선

- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/NewPostRequest.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostUpdateRequest.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
> feat: 게시글 작성시 이미지 이름 받는 기능 추가

- frontend/webpack/webpack.config.js
> feat: 이미지 API URL 변경

- frontend/src/components/PostForm/components/ImageUpload/index.tsx
> chore: 이미지 크기 상향 조정

- .gitattributes
> chore: github 언어 통계에서 html 제거

- .gitattributes
> chore: github 언어 통계에서 html 제거 (#572)

- README.md
README.md 수정(헌치)
resolved: #574
> docs: README.md 수정(헌치)

- backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/logging/LoggingAspect.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/logging/NoLogging.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/controller/MemberController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/AuthInterceptor.java
request 요청을 로깅하는 기능 구현### 세부 구현기능
> feat: request 요청을 로깅하는 기능 구현

- backend/sokdak/src/docs/asciidoc/index.adoc
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/domain/PostLike.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/LikeRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/PostLikeRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/main/resources/static/index.html
- backend/sokdak/src/test/java/com/wooteco/sokdak/admin/service/AdminServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/board/service/BoardServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/service/HashtagServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/PostLikeAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/controller/PostLikeControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/service/LikeServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/service/CommentReportServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/service/PostReportServiceTest.java
like 패키지 리팩토링
DB 테이블 컬럼명 변경 필요 #596
> refactor: like 패키지 리팩토링

- backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/logging/LoggingAspect.java
- response body 로깅
- request url 로깅
> feat: response body 로깅

- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NotificationRepository.java
NotificationRepository 불필요한 메서드 삭제
> refactor: NotificationRepository 불필요한 메서드 삭제

- frontend/src/pages/MainPage/components/Carousel/index.tsx
- frontend/src/pages/MainPage/components/Carousel/useCarousel.ts
> fix: 핫게시판에 게시물이 없을경우 캐러셀에 대한 오류

- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/config/WebMvcConfig.java
- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/Extension.java
- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/Image.java
- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/ImageCompressor.java
- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/ImageController.java
- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/ImageService.java
- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/NotSupportedExtensionException.java
- imageserver/sokdakimageserver/src/main/resources/application-local.yml
- imageserver/sokdakimageserver/src/main/resources/application.properties
- imageserver/sokdakimageserver/src/main/resources/application.yml
이미지 파일 압축 기능 구현 및 리팩터링
- 이미지 확장자 제한 (jpg, jpeg, png, gif)
- 리팩터링
- 이미지 파일 압축
> feat: 이미지 파일 압축 기능 구현 및 리팩터링

- README.md
> docs: 인프라 구조, CI/CD 이미지 추가

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/board/service/BoardService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/RoleType.java
지원자 자격 멤버로 접근 불가능한 기능(자유게시판에 글쓰기, 자유게시판 글에 댓글달기 등등) 사용 할 수 있는 버그 수정
String, Long타입 비교 ==, !=가 아닌 equals로 하도록 변경
> fix: 지원자 자격 멤버로 접근 불가능한 기능 사용할 수 있는 버그 수정

- frontend/src/components/PostForm/index.styles.ts
> feat: 디자인 수정 

- frontend/src/constants/board.ts
- frontend/src/hooks/useDebounce.ts
- frontend/src/pages/PostPage/components/CommentBox/index.tsx
- frontend/src/pages/PostPage/index.tsx
5기 게시판 이름을 변경한다.
댓글 삭제 오류를 해결한다.
좋아요 버튼에 debounce를 설정한다.
close #663
> fix: 5기 게시판 이름변경 및 댓글 삭제 오류 해결

- frontend/src/pages/PostPage/components/Sidebar/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
> refactor: 사이드바 디자인 수정

- frontend/src/pages/MainPage/components/Footer/index.styles.ts
- frontend/src/pages/MainPage/components/Footer/index.tsx
- footer에 github와 기술 블로그 링크를 추가하였습니다.
> refactor: footer 내용 수정

- README.md
> docs: 리드미 수정 

- frontend/src/dummy.ts
> feat: 광고 업데이트

- frontend/src/components/@styled/Layout/index.tsx
- frontend/src/components/Header/index.styles.ts
- frontend/src/components/PostForm/index.styles.ts
- frontend/src/pages/MainPage/components/BoardItem/index.styles.ts
- frontend/src/pages/MainPage/index.styles.ts
- frontend/src/pages/NotificationPage/index.styles.ts
- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/ProfilePage/index.styles.ts
너비가 작은 모바일 기기를 사용할 경우 좌우 스크롤이 가능해지고, 특정 UI가 잘린다.
이를 해결하기 위해 최소 너비를 축소 
close #682
> fix: UI 최소 너비 수정

- frontend/src/components/@styled/Layout/index.tsx
- frontend/src/components/Header/index.styles.ts
- frontend/src/components/PostForm/index.styles.ts
- frontend/src/constants/AD.ts
- frontend/src/dummy.ts
- frontend/src/pages/MainPage/components/BoardItem/index.styles.ts
- frontend/src/pages/MainPage/index.styles.ts
- frontend/src/pages/NotificationPage/index.styles.ts
- frontend/src/pages/PostPage/components/Sidebar/index.styles.ts
- frontend/src/pages/PostPage/index.styles.ts
- frontend/src/pages/PostPage/index.tsx
- frontend/src/pages/ProfilePage/index.styles.ts
- 작은 모바일 화면에서 UI가 깨지는 문제 개선
- 광고 업데이트
> hotfix: UI 개선 및 광고 업데이트 

- frontend/public/index.html
og:image content image가 빌드되지 않는 현상
content프로퍼티에 <%= require() %> 형식으로 삽입
close #692
> fix: og image 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/config/DataSourceConfig.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/datasource/RoutingCircular.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/support/datasource/RoutingDataSource.java
> feat: DB replication 작업

- backend/sokdak/src/docs/asciidoc/index.adoc
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/controller/PostController.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/SearchQuery.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PagePostsResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsCountResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsResponse.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
- backend/sokdak/src/main/resources/static/index.html
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/domain/AuthCodeTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/repository/PostRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
resolved: #645 
- 쿼리 검색(&, | 연산자를 통한 검색)에 대한 시간순 페이지네이션 기능 구현
- 빈 값이거나 null로 들어올 시, 모든 게시물 목록 리턴
- SQL 인젝션 대비 쿼리 필터링
> feat: 쿼리 검색 기능 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/SokdakApplication.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostRepository.java
> fix: 네이티브 쿼리 수정

- frontend/src/pages/SearchedPostPage/index.tsx
> fix: 유니코드 변환 문제 해결

- imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/util/ImageCompressor.java
> fix: 이미지가 회전되는 문제 해결

- backend/sokdak/src/main/java/com/wooteco/sokdak/auth/controller/AuthController.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/auth/domain/AuthCodeTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/board/acceptance/BoardAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/comment/acceptance/CommentAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/acceptance/HashtagAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/LikeAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/acceptance/MemberAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/EmailServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/acceptance/NotificationAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/CommentReportAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/PostReportAcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/ticket/service/RegisterServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/AcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/ServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/CommentFixture.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/PostFixture.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/TokenFixture.java
테스트 속도 개선
- 컨텍스트 캐싱을 이용해 체감 테스트 시간 개선
- 토큰을 캐싱해 로그인 요청 횟수 대폭 개선
> refactor: 테스트 속도 개선

- backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/performance/ConnectionHandler.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/performance/PerformanceAspect.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/performance/QueryCounter.java
쿼리 카운터 구현
쿼리 10개 이상 날아갈시에 warn 로깅 발송되도록 설정
> feat: 쿼리 카운터 구현

- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostRepository.java
post, comment를 찾아올때 likes를 fetch join 하는 쿼리 제거
> refactor: post, comment를 찾아올때 likes를 fetch join 하는 쿼리 제거

- backend/sokdak/src/main/java/com/wooteco/sokdak/post/controller/PostController.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
조회수 정보 저장하는 쿠기 maxAge 하루로 설정해 브라우저 꺼지면 쿠키 사라지지 않도록 함
> feat: 조회수 정보 저장하는 쿠기 maxAge 하루로 설정해 브라우저 꺼지면 쿠키 사라지지 않도록 함

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/PostListItem/index.stories.tsx
- frontend/src/pages/PostPage/components/CommentBox/index.stories.tsx
storybook을 배포한다. 
[배포 주소](https://635cf15020936c4e15ad77f9-xbgsakdyww.chromatic.com/) 
close #727
> feat: storybook 배포 

- frontend/src/hooks/queries/member/useIDCheck.ts
- frontend/src/hooks/queries/member/useLogout.ts
로그아웃시 흰 화면이 렌더링 되는 버그 해결
- suspense로 감싸진 컴포넌트 안에서 상태 변경이 이루어져 발생한 문제
1. Suspense mounts
2. child component mounts
3. usQuery throws the Promise
4. component unmounts, is replaced by suspense fallback
5. onSuccess is called, tries to setState on an unmounted component, which does nothing
6. promise completes, fallback unmounts, component mounts again
7. useState re-initializes with the default value
close #741
> fix: 로그아웃 에러 문제 해결

- backend/sokdak/src/main/java/com/wooteco/sokdak/member/service/MemberService.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/domain/NewNotificationExistence.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NewNotificationExistenceRepository.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/MemberServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/repository/NewNotificationExistenceRepositoryTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/DatabaseCleaner.java
새알림 체크 기능 exists 쿼리에서 별도 테이블로 분리
> refactor: 새알림 체크 기능 exists 쿼리에서 별도 테이블로 분리

- backend/sokdak/src/test/java/com/wooteco/sokdak/util/AcceptanceTest.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/util/ServiceTest.java
DB 초기화 시점을 @BeforeEach에서 @AfterEach로 수정
#754
> fix: DB 초기화 시점을 @BeforeEach에서 @AfterEach로 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/board/event/PostHotBoardEvent.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/event/NewCommentEvent.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/comment/event/NewReplyEvent.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NewNotificationEventHandler.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/report/event/CommentReportEvent.java
- backend/sokdak/src/main/java/com/wooteco/sokdak/report/event/PostReportEvent.java
Event 객체 필드명 수정
리뷰 반영하고 푸시하고 머지했어야 했는데, 그냥 머지해서 따로 PR 올립니다~
> refactor: Event 객체 필드명 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/notification/handler/NewNotificationEventHandler.java
- backend/sokdak/src/test/java/com/wooteco/sokdak/notification/handler/NewNotificationEventHandlerTest.java
- 알림 저장시 저장할만한 알림인지에 대한 조건문을 메서드로 추출
- Intellij에서 커밋시 자동 개행한 것을 수정
- EventListener의 패키지를 service에서 새로운 handler 패키지로 수정
> refactor: 알림 저장 로직 가독성 개선, 개행 정리 및 Listener 패키지 수정

- backend/sokdak/src/main/java/com/wooteco/sokdak/support/datasource/RoutingDataSource.java
DB 레플리케이션 profile 설정 변경
DB 서버 하나로 임시 세팅
> chore: DB 레플리케이션 profile 설정 변경

- frontend/src/api/fetcher/auth.ts
- frontend/src/api/fetcher/index.ts
- frontend/src/mocks/handlers/comments/index.ts
- frontend/src/mocks/handlers/hashtags/index.ts
- frontend/src/mocks/handlers/members/index.ts
- frontend/src/mocks/handlers/notifications/index.ts
- frontend/src/mocks/handlers/posts/index.ts
- frontend/webpack/webpack.prod.js
> feat: API prefix 변경
