woowacourse-teams/2022-sokdak

frontend/.storybook/preview-body.html
Storybook 사용시 html파일에 snackbar id를 갖는 div 태그가 존재하지 않아 스토리북이 켜지지 않는 오류 발생
어떤 상황에서 버그가 발생했는지 시나리오를 적어주세요 :  
1. npm run storybook을 한다.
2. Snackbar Template을 클릭한다.
3. 오류가 발생한다.
close #18
=> fix: Storybook사용시 SnackBar 오류 해결

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/Header/index.styles.ts, frontend/src/components/Header/index.tsx, frontend/src/index.tsx, frontend/src/pages/CreatePostPage/index.stories.tsx, frontend/src/pages/CreatePostPage/index.styles.ts, frontend/src/pages/CreatePostPage/index.tsx, frontend/src/pages/MainPage/index.stories.tsx, frontend/src/pages/MainPage/index.styles.ts, frontend/src/pages/MainPage/index.tsx, frontend/src/pages/PostPage/index.stories.tsx, frontend/src/pages/PostPage/index.styles.ts, frontend/src/pages/PostPage/index.tsx, frontend/src/style/GlobalStyle.tsx
=> feat: 페이지 라우팅 기능 구현 

frontend/src/components/@styled/Layout/index.tsx, frontend/src/components/FAB/index.styles.ts, frontend/src/components/FAB/index.tsx, frontend/src/components/Header/index.styles.ts, frontend/src/dummy.ts, frontend/src/pages/MainPage/index.styles.ts, frontend/src/pages/MainPage/index.tsx, frontend/src/style.d.ts, frontend/src/types/post.d.ts
=> feat: MainPage 구현

frontend/src/components/Header/index.stories.tsx, frontend/src/pages/CreatePostPage/index.stories.tsx
- router로 감싸진 페이지를 storybook에서 render하면 오류가 발생함.
어떤 상황에서 버그가 발생했는지 시나리오를 적어주세요 :  
1. createPostPage, Header 관련된 컴포넌트 스토리로 이동한다.
2. 라우팅 관련 오류가 발생한다. 
close #28
=> fix: storybook routing 문제 해결

frontend/src/components/PostListItem/index.styles.ts, frontend/src/components/PostListItem/index.tsx, frontend/src/pages/MainPage/index.tsx, frontend/src/pages/PostPage/index.stories.tsx, frontend/src/pages/PostPage/index.styles.ts, frontend/src/pages/PostPage/index.tsx
=> feat: PostPage 구현

frontend/src/components/PostListItem/index.tsx, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/CreatePostPage/index.tsx, frontend/src/pages/MainPage/index.tsx
- MainPage내의 글 목록 불러오기를 모킹한 API와 연결한다.
close #39
=> feat:MainPage 글목록 API 연결

backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
Sort 기준을 넘겨주지 않아서 정렬이 되지 않았습니다.
1. 첫번째 글 등록
2. 두번째 글 등록
3. 게시글 목록 조회
4. 첫번째 글, 두번째 글 순으로 조회됨
=> fix: 게시글의 시간 기준 내림차순이 되지 않았던 문제 해결

backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/BaseTimeEntity.java
저장 날짜에 대한 기능을 구현하는 과정에 존재했던 BaseTimeEntity가 불필요해져서 삭제하였습니다.
=> refactor: 불필요한 클래스 삭제

frontend/src/constants/queries.ts, frontend/src/hooks/queries/post/useCreatePost.ts, frontend/src/hooks/queries/post/usePost.ts, frontend/src/hooks/queries/post/usePosts.ts, frontend/src/pages/CreatePostPage/index.tsx, frontend/src/pages/MainPage/index.tsx, frontend/src/pages/PostPage/index.tsx
- API 관련 로직을 custom hook으로 분리한다.
- query key 관리를 쉽게 할 수 있다.
- query의 default option을 설정할 수 있다.
close #57
=> refactor: API 로직 hook으로 분리

frontend/webpack/webpack.config.js
콘솔을 열면 아래와 같이 에러가 출력된다.
```
devtools failed to load source map
```
어떤 상황에서 버그가 발생했는지 시나리오를 적어주세요 :  
1. 서버를 실행한다. 
2. 콘솔을 연다.
3. `devtools failed to load source map` 에러가 발생한다. 
```js 
// webpack.config.js
devtool : 'source-map'
```
을 추가함으로써 해결했다.
=> fix: devtool이 source-map을 인식하지 못하는 문제 해결

frontend/src/constants/snackbar.ts, frontend/src/hooks/queries/post/useCreatePost.ts
`SNACKBAR_MESSAGE`가 export되어 있지 않아 `SNACKBAR_MESSAGE`를 찾을 수 없다는 에러가 발생한다. 
`SNACKBAR_MESSAGE`를 export 해주고, 사용처에서 import 해줌
close #75
=> fix: snackbar 관련 상수 export

frontend/src/App.tsx, frontend/src/components/PostForm/index.stories.tsx, frontend/src/components/PostForm/index.styles.ts, frontend/src/components/PostForm/index.tsx, frontend/src/constants/path.ts, frontend/src/constants/snackbar.ts, frontend/src/hooks/queries/post/useUpdatePost.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/CreatePostPage/index.styles.ts, frontend/src/pages/CreatePostPage/index.tsx, frontend/src/pages/PostPage/index.styles.ts, frontend/src/pages/PostPage/index.tsx, frontend/src/pages/UpdatePostPage/index.stories.tsx, frontend/src/pages/UpdatePostPage/index.styles.ts, frontend/src/pages/UpdatePostPage/index.tsx, frontend/src/style/GlobalStyle.tsx, frontend/src/style/theme.ts, frontend/src/types/style.d.ts
작성된 글을 수정할 수 있는 기능을 구현한다.
close #72 
1. [feat: PostForm 컴포넌트 구현](https://github.com/woowacourse-teams/2022-sokdak/commit/b8c30214aef5dae7123427c6f41dac38ca04aa44)
a. 글 작성 페이지와 글 수정 페이지가 공통적으로 사용할 수 있도록 `PostForm` 컴포넌트 구현
2. [feat: PostForm 컴포넌트를 CreatePostPage에 활용](https://github.com/woowacourse-teams/2022-sokdak/commit/4f52c07e2353a390ba32de102331794dff57d1d0)
a. 구현한 PostForm 컴포넌트를 CreatePostPage에 적용
3. [feat: 게시물을 수정하는 페이지인 UpdatePostPage 컴포넌트 구현](https://github.com/woowacourse-teams/2022-sokdak/commit/629eacc4042f08f8b72cf2309286dfffa155a8a7) 
a. 글 수정 페이지(UpdatePostPage)의 UI만 구현
4. [feat: 수정 API msw mocking 구현](https://github.com/woowacourse-teams/2022-sokdak/commit/e26d518700513ca96a414b3ca76269cbc97ea099)
5. [feat: 수정 API를 위한 custom hook …
=> feat: 게시물 수정 기능 구현

frontend/.storybook/preview-body.html, frontend/public/index.html, frontend/src/components/ConfirmModal/index.stories.tsx, frontend/src/components/ConfirmModal/index.styles.ts, frontend/src/components/ConfirmModal/index.tsx, frontend/src/constants/snackbar.ts, frontend/src/hooks/queries/post/useDeletePost.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/PostPage/index.tsx
작성된 글을 삭제할 수 있는 기능을 구현한다.
close #73
=> feat: 게시물 삭제 기능 구현 

backend/sokdak/src/main/java/com/wooteco/sokdak/config/WebMvcConfig.java, backend/sokdak/src/main/java/com/wooteco/sokdak/support/AuthInfoMapper.java, backend/sokdak/src/main/java/com/wooteco/sokdak/support/LoginArgumentResolver.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java
`Object` -> `AuthInfo` 매핑 부분이 `Mock` 객체에서는 진행되지 않아 
일단 매핑용 빈(`AuthInfoMapper`)을 추가하고, 테스트 코드에서 `@MockBean`으로 설정함
(해당 방식은 ArgumentResolver를 목으로 만든 것으로, 통합테스트라고 볼 순 없음)
- 앞으로 `RestAssuredMockMvc`에서 세션 값 매핑이 이뤄질 때 마다 `sessionId()`, `sessionAttribute()`를 설정해주면 됨
- 컨트롤러 테스트 범위에 대해 논의 필요
=> feat: argumentResolver 매핑용 빈 추가 및 테스트코드 반영

frontend/package.json, frontend/webpack/webpack.config.js, frontend/webpack/webpack.dev.js
=> chore: production용 webpack 설정

backend/sokdak/src/main/java/com/wooteco/sokdak/advice/ControllerAdvice.java, backend/sokdak/src/main/java/com/wooteco/sokdak/advice/ForbiddenException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/exception/AuthenticationException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/exception/MemberNotFoundException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/controller/PostController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsElementResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/support/AuthInfoMapper.java, backend/sokdak/src/main/java/com/wooteco/sokdak/support/LoginArgumentResolver.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/util/PostFixture.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
=> feat: 회원과 게시물 연관관계 매핑

frontend/src/components/HashTag/index.styles.ts, frontend/src/components/HashTag/index.tsx, frontend/src/components/PostForm/index.styles.ts, frontend/src/components/Snackbar/index.styles.ts, frontend/src/pages/PostPage/index.styles.ts, frontend/src/pages/PostPage/index.tsx
글 상세보기 페이지에서 해당 글에 달려있는 태그를 표시한다.
close #128
=> feat: 글 상세보기 페이지에서 해쉬태그 표시

frontend/src/components/LikeButton/index.styles.ts, frontend/src/components/LikeButton/index.tsx
하트 svg 크기가 좋아요 수에 따라 달라지는 문제를 해결
close #138
=> fix: 좋아요 수에 따라 하트 svg 크기가 달라지지 않도록 수정

backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
게시글 삭제 시 해시태그 관련 오류 해결
관련해 메소드를 빼면 좋을 것 같습니다.
=> fix: 게시글 삭제 시 해시태그 관련 오류 FIX #143

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/LikeRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
좋아요/댓글 있는 경우 게시글 삭제 안되는 버그 수정
- post를 삭제하기 전에 댓글/좋아요를 삭제하고 삭제하도록 구현
- post에서 Cascade remove 옵션을 줬는데 동작하지 않음
- 이번 스프린트 이후 수정해야함
=> fix: 좋아요/댓글 있는 경우 게시글 삭제 안되는 버그 수정

backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostHashtagRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/HashtagAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
한번만 쓰인 해시태그와 연결된 게시글이 삭제될 시,
해당 해시태그들이 Hashtag 테이블에서 삭제된다.
해시태그 삭제는 특정 게시물 삭제 시마다,
게시물에 존재했던 해시태그들에 대해 이뤄진다.
=> feat: 사용되지 않는 해시태그 삭제

backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Nickname.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/exception/InvalidNicknameException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/domain/member/NicknameTest.java
=> feat: 닉네임 포맷 확인 기능 추가

backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/HashtagConverter.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java
해시태그 기능 관련 1차 리팩토링 진행
resolved: #160 
- 해시태그 유틸을 `@Component` 등록함
- 아직 해시태그 관련 패키지 이동을 진행하지 않은 pr
=> feat: 해시태그 기능 1차 리팩토링 #160

backend/sokdak/src/test/java/com/wooteco/sokdak/util/AcceptanceTest.java, backend/sokdak/src/test/resources/application.yml, backend/sokdak/src/test/resources/truncate.sql
`AcceptanceTest`에서 `@DirtiesContext` 초기화 문제 해결을 위해 `@Sql`문 사용
`truncate.sql`로 초기화
resolved: #188
=> fix: 테스트 격리 문제 해결 FIX #188

backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/controller/HashtagController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/repository/HashtagRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/repository/PostHashtagRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/service/HashtagService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsResponse.java, backend/sokdak/src/test/java/com/wooteco/sokdak/board/service/BoardServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/acceptance/HashtagAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/controller/HashtagControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/repository/PostHashtagRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/service/HashtagServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/service/LikeServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/EmailServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/ControllerTest.java, backend/sokdak/src/test/resources/truncate.sql
해시태그로 검색 기능 구현 및 테스트 격리를 위해 추가 조치
resolved: #172
[테스트 격리 관련 노션 링크](https://utopian-galley-07b.notion.site/88edd0ef360e4fb3b55e5123a6bc9067)
=> feat: 해시태그로 검색 기능 구현 #172

backend/sokdak/src/main/java/com/wooteco/sokdak/config/WebMvcConfig.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/controller/HashtagController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/dto/HashtagSearchElementResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/dto/HashtagsSearchRequest.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/dto/HashtagsSearchResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/repository/HashtagRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/repository/PostHashtagRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/service/HashtagService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/acceptance/HashtagAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/controller/HashtagControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/repository/HashtagRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/repository/PostHashtagRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/service/HashtagServiceTest.java
- 키워드로 검색하면 해당 키워드가 포함된 해시태그 목록을 반환하는 기능 구현
- 인터셉터에 "/hashtags/**" 주소를 토큰 검증에서 제외시킴
resolved: #171 
- `BE` 브랜치로 재 리베이스 후 pr 다시 날렸습니다!
- `PostHashtagRepository`에서 JPQL 사용
=> feat: 해시태그 목록 조회 기능 구현 #171

backend/sokdak/src/main/java/com/wooteco/sokdak/board/controller/BoardController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/board/dto/BoardContentElement.java, backend/sokdak/src/main/java/com/wooteco/sokdak/board/dto/BoardContentPostElement.java, backend/sokdak/src/main/java/com/wooteco/sokdak/board/dto/BoardContentResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/board/service/BoardService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/test/java/com/wooteco/sokdak/board/acceptance/BoardAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/board/controller/BoardControllerTest.java
메인페이지 조회 기능 구현
가져오는 데이터 json 구조가 복잡하여 Dto 이름들이 헷갈릴 수도 있을 것 같습니다. 혹시 좋은 아이디어 있으면 언제든지 제시 부탁드립니다.
=> feat: 메인페이지 조회 기능 구현

backend/sokdak/src/test/resources/truncate.sql
truncate.sql 을 수정하여 테스트 격리를 했습니다.
=> fix: 테스트 격리를 위한 truncate.sql 수정

frontend/src/components/PostListItem/index.tsx, frontend/src/constants/path.ts, frontend/src/constants/queries.ts, frontend/src/dummy.ts, frontend/src/hooks/queries/post/usePostsByBoard.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/MainPage/components/BoardItem/index.stories.tsx, frontend/src/pages/MainPage/components/BoardItem/index.styles.ts, frontend/src/pages/MainPage/components/BoardItem/index.tsx, frontend/src/pages/MainPage/index.stories.tsx, frontend/src/pages/MainPage/index.styles.ts, frontend/src/pages/MainPage/index.tsx, frontend/src/types/post.d.ts
- 메인페이지 UI 변경에 따른 게시판 분리 기능 및 UI 구현
close #242
=> feat:MainPage 기능 변경

backend/sokdak/build.gradle, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/domain/AuthCode.java, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/util/TimeConfig.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/domain/AuthCodeTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/service/AuthServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/controller/MemberControllerTest.java
인증코드의 시간을 체크해, 만료된 인증코드를 사용할 수 없게 한다
resolved: #229 
- 회원가입 관련 인수테스트, 서비스테스트 미흡
- 관련 인수테스트 위치 고민
=> feat: 인증코드 시간 만료 #229

frontend/src/components/CheckBox/index.stories.tsx, frontend/src/components/CheckBox/index.styles.ts, frontend/src/components/CheckBox/index.tsx, frontend/src/components/PostForm/index.styles.ts, frontend/src/components/PostForm/index.tsx, frontend/src/dummy.ts, frontend/src/hooks/queries/post/useCreatePost.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/PostPage/components/PostHeader/index.tsx, frontend/src/types/post.d.ts
게시물 작성시 익명 혹은 기명을 선택할 수 있는 기능을 구현한다.
- 게시물을 수정할 경우에는 익명 / 기명을 변경할 수 없다. 
close #272
=> feat: 게시물 작성시 익명/기명을 선택할 수 있는 기능 구현

backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/NewPostRequest.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/board/acceptance/BoardAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/acceptance/CommentAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/acceptance/HashtagAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/hashtag/service/HashtagServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/LikeAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/controller/PostControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/util/PostFixture.java, backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/CommentReportAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/report/acceptance/PostReportAcceptanceTest.java
=> feat: 게시글 작성시 익명/기명 선택 기능 구현

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/dto/CommentResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/domain/Member.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/controller/CommentControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
게시글 작성자 댓글 식별 기능 구현
- 게시글 익명(랜덤 닉네임)으로 작성 (ex : 짜증난 파이썬)
- 작성자가 익명으로 댓글 작성 : 게시글 닉네임과 동일한 랜덤 닉네임
- 작성자가 기명으로 댓글 작성 : 작성자의 회원 정보에 있는 닉네임 반환
- 게시글 기명으로 작성 
- 작성자가 익명으로 댓글 작성 : 랜덤 닉네임 반환
- 작성자가 기명으로 댓글 작성 : 작성자의 회원 정보에 있는 닉네임 반환
모든 댓글에 대해, 게시글 작성자가 작성한 댓글 여부 반환
=> feat: 게시글 작성자 댓글 식별 기능 구현

frontend/src/constants/board.ts, frontend/src/dummy.ts
게시판 목록에서 게시판 순서를 API 명세와 동일하게 한다.
1. Hot 게시판
2. 자유 게시판
3. 포수타
4. 감동크루 
close #286
=> fix: 게시판 순서를 API 명세를 따라 수정

frontend/src/dummy.ts, frontend/src/hooks/queries/comment/useComments.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/PostPage/components/CommentBox/index.styles.ts, frontend/src/pages/PostPage/components/CommentBox/index.tsx, frontend/src/pages/PostPage/components/CommentList/index.tsx
글 작성자가 본인의 글에 댓글을 달았을 경우 작성자를 표기해준다. 
close #294
=> feat: 댓글에 작성자 표기

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/main/resources/logback/file-access-logger.xml, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/repository/MemberRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/service/PostServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java
게시글 닉네임 유니크 제약조건 변경
기존 코드에서 회원 닉네임/ 댓글 닉네임/게시글 닉네임을 모두 같은 '닉네임' 객체를 쓰고 있었다.
그래서 유니크 제약 조건을 거니 테스트 코드가 다 깨졌다. 댓글과 게시글에서는 닉네임을 값 객체를 쓰지 않고
String으로 저장하도록 변경했다.
=> fix: 댓글/게시글의 닉네임과 회원 닉네임 분리

frontend/src/pages/PostPage/components/PostHeader/index.tsx, frontend/src/pages/PostPage/components/ReportModal/index.tsx
중복 신고시 에러 response가 스낵바에 그대로 노출되는 문제 해결
=> fix: 중복 신고 예외 메시지 처리

frontend/src/pages/BoardPage/components/BoardCategory/index.styles.ts, frontend/src/pages/BoardPage/components/BoardCategory/index.tsx
게시판 드롭다운에 특정 게시판에 해당하는 이모지를 추가한다.
close #352
=> fix: 게시판 드롭다운에 이모지 추가

backend/sokdak/src/test/java/com/wooteco/sokdak/util/IntegrationTest.java
서비스 테스트 깨짐 해결
IntegrationTest와 이를 상속받는 클래스에서 @BeforeEach 메서드명이 같아 override됨
=> refactor: 서비스 테스트 깨짐 해결

backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostDetailResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/PostsElementResponse.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java
신고 처리된 게시글 제목과 본문 가려서 반환
데이터베이스에서는 변환될 필요가 없으므로 뷰의 로직이라고 생각했습니다. 따라서 Dto에서 신고 여부에 따라 변환해서 값을 반환합니다.
=> feat: 신고 처리된 게시글 제목과 본문 가려서 반환

backend/sokdak/src/docs/asciidoc/index.adoc, backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/profile/controller/ProfileController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/profile/dto/MyPostsResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/profile/service/ProfileService.java, backend/sokdak/src/main/resources/static/index.html, backend/sokdak/src/test/java/com/wooteco/sokdak/post/repository/PostRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/profile/acceptance/ProfileAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/profile/controller/ProfileControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/profile/service/ProfileServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/PostFixture.java
프로필 페이지에서 내가 쓴 글 목록을 조회할 수 있다.
resolved: #392
=> feat: 프로필에서 내가 쓴 글 보기 #392

frontend/src/constants/queries.ts, frontend/src/constants/scroll.ts, frontend/src/dummy.ts, frontend/src/hooks/queries/comment/useComments.ts, frontend/src/hooks/queries/comment/useCreateReply.ts, frontend/src/hooks/queries/comment/useDeleteComment.ts, frontend/src/mocks/handlers/comments/index.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/mocks/worker.ts, frontend/src/pages/PostPage/components/CommentBox/index.styles.ts, frontend/src/pages/PostPage/components/CommentBox/index.tsx, frontend/src/pages/PostPage/components/CommentInput/index.tsx, frontend/src/pages/PostPage/components/CommentList/index.styles.ts, frontend/src/pages/PostPage/components/CommentList/index.tsx, frontend/src/pages/PostPage/components/ReplyForm/index.stories.tsx, frontend/src/pages/PostPage/components/ReplyForm/index.styles.ts, frontend/src/pages/PostPage/components/ReplyForm/index.tsx, frontend/src/style/theme.ts, frontend/src/types/api.d.ts, frontend/src/types/comment.d.ts, frontend/src/types/style.d.ts, frontend/src/utils/scrollToCurrent.ts
댓글에 대한 답글을 작성할 수 있는 대댓글 기능을 구현한다. 
- 순회 중단이 필요할 경우 `forEach`는 적절하지 않다. 배열이라면 `for of`를 사용할 것
- `commentCount`와 comment의 id는 분리되어야 한다. (commentId는 계속 증가하지만, count는 감소할 수 있음)
- resetQuery와 refetchQuery의 차이 (스크롤 초기화)
close #401
=> feat: 대댓글 기능 구현

backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/domain/Hashtags.java, backend/sokdak/src/main/java/com/wooteco/sokdak/hashtag/service/HashtagService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/dto/MyPostsResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java
resolved: #423 
정적 팩토리 메소드명 변경 of으로 변경
하나의 클래스에 같은 형태의 파라미터의 정적 팩토리메소드가 여러 개 있을 경우 이름 변경하지 않음
=> refactor: 정적 팩토리 메소드명 변경 #423

frontend/src/setupTests.ts
대댓글 구현 이후 댓글 관련 테스트가 깨진다. 
close #433
=> fix: 깨지는 FE 테스트 해결

frontend/src/hooks/queries/notification/useDeleteNotification.ts
- 알림 삭제시 서버와의 데이터 동기화 문제 때문에 발생하는 데이터 Fetching 오류 해결
- 알림 delete시 setqueriesData -> refetchQueries로 변경
close #470
=> fix: 알림 delete시 데이터 동기화 문제 수정

backend/sokdak/src/docs/asciidoc/index.adoc, backend/sokdak/src/main/java/com/wooteco/sokdak/SokdakApplication.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/controller/AdminController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/EmailsAddRequest.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/PostReportElement.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/PostReportsResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/TicketElement.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/TicketRequest.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/TicketsResponse.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/exception/NoAdminException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/service/AdminService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/domain/Ticket.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/util/TimeConfig.java, backend/sokdak/src/main/java/com/wooteco/sokdak/report/repository/PostReportRepository.java, backend/sokdak/src/main/resources/static/index.html, backend/sokdak/src/test/java/com/wooteco/sokdak/admin/acceptance/AdminAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/admin/controller/AdminControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/admin/service/AdminServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/ControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/IntegrationTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/HttpMethodFixture.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/MemberFixture.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/PostFixture.java
admin 전용 api를 구현한다
resolved: #421
=> feat: admin api 구현

frontend/src/context/Auth.tsx, frontend/src/dummy.ts, frontend/src/hooks/queries/comment/useLikeComment.ts, frontend/src/mocks/handlers/comments/index.ts, frontend/src/pages/PostPage/components/CommentBox/index.stories.tsx, frontend/src/pages/PostPage/components/CommentBox/index.styles.ts, frontend/src/pages/PostPage/components/CommentBox/index.tsx, frontend/src/types/comment.d.ts
- 댓글 및 대댓글에 대한 좋아요 기능을 구현한다.
- setQuriesData()를 사용하여 로직이 상당히 복잡함.
- axios의 모든 config들을 캐싱해 놓을 필요가 있을까? #492
close #479
=> feat: 댓글 좋아요 UI 및 API 연결 구현

frontend/src/App.tsx, frontend/src/components/@shared/Dropdown/index.tsx, frontend/src/components/Header/index.styles.ts, frontend/src/components/Header/index.tsx, frontend/src/components/Pagination/index.stories.tsx, frontend/src/components/Pagination/index.styles.ts, frontend/src/components/Pagination/index.tsx, frontend/src/components/PostCountInfo/index.stories.tsx, frontend/src/components/PostCountInfo/index.styles.ts, frontend/src/components/PostCountInfo/index.tsx, frontend/src/components/PostListItem/index.tsx, frontend/src/constants/path.ts, frontend/src/constants/queries.ts, frontend/src/constants/snackbar.ts, frontend/src/context/Pagination.tsx, frontend/src/dummy.ts, frontend/src/hooks/queries/member/useUpdateNickname.ts, frontend/src/hooks/queries/profile/useMyPosts.ts, frontend/src/hooks/queries/profile/useUpdateNickname.ts, frontend/src/index.tsx, frontend/src/mocks/handlers/members/index.ts, frontend/src/mocks/handlers/posts/index.ts, frontend/src/pages/MainPage/components/BoardItem/index.tsx, frontend/src/pages/ProfilePage/components/PostItem/index.stories.tsx, frontend/src/pages/ProfilePage/components/PostItem/index.styles.ts, frontend/src/pages/ProfilePage/components/PostItem/index.tsx, frontend/src/pages/ProfilePage/index.stories.tsx, frontend/src/pages/ProfilePage/index.styles.ts, frontend/src/pages/ProfilePage/index.tsx
사용자 프로필 페이지를 구현한다. 
- post안 count 관련 정보들이 중복돼서 사용되는 곳이 많아, 컴포넌트를 분리해서 재활용했습니당. (PostCountInfo 컴포넌트로 분리했습니다.)
- msw mocking handler를 작성할 때 `post/me` 관련 핸들러가 `post/:id`로 간주가 되더라구요. 이 부분에 대해 백앤드 크루에게 물었더니 백앤드에서는 타입으로 분기가 된다고 하여 타입으로 분기하긴 했는데 더 좋은 방법을 고민중입니다 🤔
- 리팩토링할 부분이 많은 것 같은데 이 부분을 중점적으로 리뷰해주시면 감사하겠습니당~!
close #426
=> feat: 프로필 페이지 구현 

frontend/src/hooks/queries/profile/useUpdateNickname.ts, frontend/src/mocks/handlers/members/index.ts, frontend/src/pages/ProfilePage/index.styles.ts, frontend/src/pages/ProfilePage/index.tsx
- 닉네임 수정에 실패한 경우에 대한 예외처리 추가 
- `isAnimationActive`를 state로 선언하지 않고 query가 뱉는 `isError`를 사용하면 쉽게 후덜덜 애니메이션을 적용할 수 있습니다.
```jsx
const { isError } = useQuery ...
<Input 
isAnimationActive={isError}
/>
```
close #502
=> fix: 닉네임 수정 예외 처리

frontend/src/pages/BoardPage/components/BoardCategory/index.styles.ts
게시판 이름이 짤려 개행되는 문제 개선
close #508
=> fix: 게시판 이름이 짤려 개행되는 문제 해결

frontend/src/pages/ProfilePage/components/PostItem/index.styles.ts
프로필 안 내가 쓴 글에서 긴 글에 개행/숨김 처리를 추가한다.
close #510
=> fix: 내가 쓴 글에서 긴 글 개행/숨김 처리 추가

.github/workflows/backend.yml
자바레벨에서 타임존 설정이 먹히는지 확인하기 위해 깃헙액션 타임존 설정 스크립트 제거
=> chore: 깃헙액션 타임존 설정 스크립트 제거

frontend/src/components/SearchModal/index.tsx, frontend/src/pages/PostPage/components/PostContent/index.tsx
- 글 상세페이지에서 해시태그를 클릭하면 해당 검색페이지로 이동한다.
close #511
=> feat: 상세페이지에서 해시태그 클릭시 해당 검색페이지로 이동

frontend/src/hooks/queries/profile/useUpdateNickname.ts, frontend/src/pages/ProfilePage/index.tsx
닉네임 변경시 토큰이 재발급되므로 토큰을 재설정한다. 
- `닉네임을 수정하고 로그아웃 후 확인해보면 닉네임이 알 수 없는 문자로 되어 있다.` 이건 파싱에러라 다른 PR에서 해결합니다. 
- 헌치가 아직 토큰 재발급 코드를 작성중이라 merge가 되어도 `dev`에서 확인할 수 없습니다. 
close #518
=> fix: 닉네임 변경시 토큰을 재설정 하도록 변경

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/service/CommentServiceTest.java
기명 게시글에서 작성자가 익명 댓글을 여러번 달아도 동일한 닉네임 할당되지 않던 버그 수정
fix #524
=> fix: 기명 게시글에서 작성자가 익명 댓글을 여러번 달아도 동일한 닉네임 할당되지 않던 버그 수정

backend/sokdak/src/main/java/com/wooteco/sokdak/member/controller/MemberController.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/acceptance/MemberAcceptanceTest.java
닉네임 수정 시 새로 토큰을 발급해 반환하도록 변경
resolve: #526
=> fix: 닉네임 수정 시 새로 토큰을 발급해 반환하도록 변경

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/acceptance/CommentAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/report/service/CommentReportServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/report/service/PostReportServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/PostFixture.java
블라인드 된 게시글 작성자 닉네임의 응답값이 원래 작성자 닉네임이었는데, 이를 블라인드 처리되었다는 메시지로 수정
또한, 게시글과 댓글의 블라인드 메시지를 변경했습니다.
=> feat: 블라인드 된 게시글의 작성자 닉네임 응답값 수정

frontend/src/hooks/queries/post/useCreatePost.ts, frontend/src/hooks/queries/post/useDeletePost.ts, frontend/src/hooks/queries/post/useUpdatePost.ts, frontend/src/index.tsx, frontend/src/pages/BoardPage/index.tsx, frontend/src/pages/MainPage/index.tsx, frontend/src/pages/PostPage/index.tsx, frontend/src/pages/ProfilePage/index.tsx
react-query 캐싱 기능을 이용하여 API 호출을 최적화한다. 
<details>
<summary>페이지네이션 데이터를 가져올 때 이전 페이지를 캐싱한다.</summary>
[feat: 페이지 이동시 이전 페이지 데이터 유지](https://github.com/woowacourse-teams/2022-sokdak/commit/0f81b74729da6a8c920f0abfe30db663e697895d)
기존에는 이미 봤던 페이지로 이동하더라도 새로 페이지를 가져왔습니다. 
이는 캐싱 설정을 하지 않았기 때문입니다. 
이번 구현에서는 staleTime을 설정해주어 캐싱을 진행했습니다. 
> staleTime vs cacheTime
> 
> **staleTime** : 데이터의 신선한 상태가 언제까지 지속될지 (default 0 = 즉시 stale하다고 판단하여 데이터와 무관하게 fetching)  
> **cacheTime** : 메모리에 저장된 캐시 데이터가 언제까지 유지될지 알려주는 옵션  (default 5분, inactive 상태일 때 메모리에 캐시를 언제까지 유지할 지) 
- staleTime 설정 기준?
- 현재 staleTime을 Infinity로 설정해주었습니다. 이유는 사용자가 프로필 페이지에 있는 이상 새로운 글을 작성할 일이 없다고 판단했습니다. 
- staleTime은 Infinity로 설정 되어있지만 글이 등록/삭제/수정되었을 때 resetQueries를 통해 캐시가 무효화되도록 설정해주었습니다. 
</details>
<details>
<summary>(게시판 + 각 게시판 최신글 …
=> feat: react-query 캐싱 기능을 이용하여 API 호출 최적화 

frontend/package.json, frontend/public/index.html, frontend/src/style/GlobalStyle.tsx, frontend/src/types/file.d.ts, frontend/webpack/webpack.config.js
새로고침 시 폰트가 적용되지 않는 문제 
메인 페이지가 아닌 다른 url로 접속하고 새로고침을 하면 해당 url기준으로 폰트 요청이 날라감
이는 preload를 위한 index.html내 link태그의 href에 경로 설정 문제로 인해 발생함
interpolate-html-plugin을 통해 PUBLIC_URL 변수를 index.html로 전달하고 이를 href에 활용함으로써 새로고침 후에도 PUBLIC_URL을 참조하도록 설정
close #548
=> fix: 새로고침시 폰트가 적용되지 않는 문제 해결

frontend/package-lock.json, frontend/package.json, frontend/src/App.tsx, frontend/src/components/@shared/Dropdown/index.tsx, frontend/src/components/@shared/InputBox/components/Input/index.tsx, frontend/src/components/@shared/InputBox/components/SubmitButton/index.tsx, frontend/src/components/@shared/InputBox/index.tsx, frontend/src/components/@shared/InputBox/useInputContext.tsx, frontend/src/components/@shared/Modal/index.tsx, frontend/src/components/CheckBox/index.tsx, frontend/src/components/Pagination/index.tsx, frontend/src/components/PostForm/components/HashTagInput/index.tsx, frontend/src/context/Auth.tsx, frontend/src/context/Pagination.tsx, frontend/src/context/Snackbar.tsx, frontend/src/hooks/queries/member/useLogin.ts, frontend/src/hooks/queries/member/useLogout.ts, frontend/src/hooks/queries/profile/useUpdateNickname.ts, frontend/src/style/GlobalStyle.tsx
-  유틸 타입을 분리하고 [속닥 유틸 타입](https://www.npmjs.com/package/sokdak-util-types)을 publish하여 이를 프로젝트에 반영한다.
```typescript
export type PropsWithChildrenC<P = unknown, C = ReactNode> = P & {
children: C;
};
export type StateAndAction<T, K extends string> = {
[P in K]: T;
} & {
[P in `set${Capitalize<K>}`]: Dispatch<SetStateAction<T>>;
};
```
#582
=> refactor: typescript 유틸 타입 npm 출시 및 분리

backend/sokdak/src/main/java/com/wooteco/sokdak/notification/domain/Notification.java, backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NotificationRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/notification/repository/NotificationRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/notification/service/NotificationServiceTest.java
- notification 조회시 반복문을 돌면서 query문을 실행하는 로직, where~in으로 개선
- comment와 post에 해당하는 Notification 삭제 로직에서 query문이 Notification의 개수만큼 실행되는 문제 where~in으로 개선
#576
=> refactor: Notification 리팩토링

frontend/public/manifest.json, frontend/src/App.tsx, frontend/src/components/Prompt/index.stories.tsx, frontend/src/components/Prompt/index.styles.ts, frontend/src/components/Prompt/index.tsx, frontend/src/constants/localStorage.ts, frontend/src/constants/snackbar.ts, frontend/src/hooks/useInstallApp.ts, frontend/src/index.tsx, frontend/webpack/webpack.config.js, frontend/webpack/webpack.dev.js, frontend/webpack/webpack.prod.js
사용자들이 손쉽게 PWA를 이용할 수 있도록 사용성을 보강한다.
- 현재 반응형 기능 개발 이후, 디자인에 대해 좀 더 고민하고 수정하겠습니다! 
- `beforeinstallprompt` 이벤트가 현재 비표준으로, type이 존재하지 않아 `// @ts-nocheck`를 해주었습니다. (hooks/useInstallApp.ts)
- 개발 환경에서 service worker를 register할 경우 cache 관련 오류가 발생하여 구글링한 결과, 개발 환경에서는 등록을 하지 않는다고 합니당. 이런 이유로 개발환경에서는 PWA를 제외시켰습니다. 현재 개발 환경에서 테스트 해볼 경우 prompt가 나타나고, 사라지는 것만 확인 가능하며 설치는 불가능합니다. - [fix: 개발 환경에서 PWA 제외](https://github.com/woowacourse-teams/2022-sokdak/commit/360e08ac92c72b5f450744cea4ae9bb5b41a0e68), [fix: 개발 환경 서비스 워커 등록 제거](https://github.com/woowacourse-teams/2022-sokdak/commit/dca4691fb4f385b45530f634ee1470a637f75d2b)
close #593
=> feat: PWA 사용성 보강

backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/TicketElement.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/TicketRequest.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/service/AdminService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/controller/AuthController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/repository/AuthCodeRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/repository/TicketRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/service/EmailService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/service/MemberService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/ticket/controller/RegisterController.java, backend/sokdak/src/main/java/com/wooteco/sokdak/ticket/domain/AuthCode.java, backend/sokdak/src/main/java/com/wooteco/sokdak/ticket/domain/Ticket.java, backend/sokdak/src/main/java/com/wooteco/sokdak/ticket/service/RegisterService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/admin/service/AdminServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/controller/AuthControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/domain/AuthCodeTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/service/AuthServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/controller/MemberControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/EmailServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/service/MemberServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/support/token/JwtTokenProviderTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/ticket/controller/RegisterControllerTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/ticket/service/RegisterServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/ControllerTest.java
Auth에 있던 인증/회원가입 관련 기능 분리
회원가입에 사용하는 인증코드 검사/티켓 사용은 ticket 패키지 하위의 RegisterController에서 처리하게 하였습니다. 패키지명을 Register로 할까하다가 우선 팀에서 회원가입할 때 ticket을 공통적으로 인지하고 있어 ticket으로 했습니다.
=> refactor: Auth에 있던 인증/회원가입 관련 기능 분리

backend/sokdak/src/main/java/com/wooteco/sokdak/notification/repository/NotificationRepository.java
native 쿼리의 테이블명(Notification)을 notification으로 수정
=> fix: native 쿼리의 테이블명(Notification)을 notification으로 수정

frontend/src/hooks/queries/likes/useLike.ts, frontend/src/pages/PostPage/components/PostHeader/index.tsx, frontend/src/pages/PostPage/index.tsx
좋아요 수가 0개로 표시되는 버그를 해결한다. 
> 버그 시나리오
> 
> 1. 특정 게시물 페이지에 들어간다.
> 2. 페이지를 나갔다가 다시 페이지에 들어간다. 
> 3. 좋아요 수가 0개로 초기화된다.
close #604
=> fix: 좋아요가 초기화되는 문제 해결

backend/sokdak/src/main/java/com/wooteco/sokdak/notification/service/NotificationService.java
findNotifications의 @Transactional readOnly 옵션 제거
=> fix: findNotifications의 @Transactional readOnly 옵션 제거

frontend/src/components/PostForm/components/ImageUpload/index.tsx, frontend/src/constants/snackbar.ts
사진 업로드 시 옵션을 눌러 모든 파일로 변경해버리면 
제한을 걸었어도 사진이 아닌 다른 확장자 파일도 선택이 가능합니다. 
이런 이유로 스크립트 코드를 추가해 한번 더 제한을 주었습니다.  
close #615
=> feat: 파일 형식 제한

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/domain/CommentLike.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/domain/PostLike.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/exception/CommentLikeNotFoundException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/exception/PostLikeNotFoundException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/PostLikeRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/LikeAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/acceptance/PostLikeAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/domain/CommentLikeTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/domain/PostLikeTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/service/LikeServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/LikeFixture.java
좋아요 기능에서의 불필요한 쿼리 삭제
Post는 PostLike와,  Comment는 CommentLike와 연관 관계를 맺고 있는데, Post와 Comment에게 메시지를 통해 값을 조회하지 않고 query를 실행하여 값을 조회했던 로직 -> query 실행이 아닌, Post와 Comment의 메서드로 처리하도록 수정
=> refactor: 좋아요 기능에서의 불필요한 쿼리 삭제

frontend/src/components/CheckBox/index.styles.ts, frontend/src/components/LikeButton/index.styles.ts, frontend/src/dummy.ts, frontend/src/hooks/useThrottle.ts, frontend/src/pages/PostPage/components/CommentBox/index.styles.ts, frontend/src/pages/PostPage/components/CommentBox/index.tsx, frontend/src/pages/PostPage/components/CommentInput/index.styles.ts, frontend/src/pages/PostPage/components/PostHeader/index.styles.ts, frontend/src/pages/PostPage/components/ReplyForm/index.styles.ts, frontend/src/pages/PostPage/components/Sidebar/components/SidebarContainer/index.styles.ts, frontend/src/pages/PostPage/components/Sidebar/components/SidebarContainer/index.tsx, frontend/src/pages/PostPage/components/Sidebar/index.stories.tsx, frontend/src/pages/PostPage/components/Sidebar/index.styles.ts, frontend/src/pages/PostPage/components/Sidebar/index.tsx, frontend/src/pages/PostPage/index.styles.ts, frontend/src/pages/PostPage/index.tsx
글 상세 페이지를 데스크탑 사이즈로 구현합니다. 
close #631 
- 현재 정적 dummy 데이터를 넣어두었습니다.! 
`em`과 `rem`를 사용했을 때, 반응형 구현이 좀 더 쉬운 이유는 `@media`로 break point에서 `html` 태그의 폰트 사이즈만 변경해주면 하위 요소의 `rem`이 전부 변경되기 때문에 편리하기 때문이라고 하네요 ! 그래서 html의 font-size를 계산하기 쉽게 10px로 지정해준다고 하네용. 
근데 이번에는 제 작업 전에 이미 rem이 사용되었고, 제가 임의로 html의 font-size를 변경한다면 rem을 사용한 부분이 모두 깨질 것이기 때문에 em과 rem을 혼용하여 사용했습니다! 
구현할까 고민하다가, 이보다 급한 작업을 먼저하는 것이 낫다고 생각이 들어 
현재는 구현하지 않았습니다!! 추후 구현하도록 하겠습니다 :) 헤헤 🤪
useEffect를 사용해 addEventListener로 넘겨준 콜백함수에서는 state는 변경사항이 반영되지 않더군요.. ㅎㅎ
만약 state가 반영되게 하려면 useEffect의 dep 배열에 콜백함수를 넣어주거나, useEffect 안에서 addEventListener를 쓰지 않으면 됩니다 ㅎ
그렇지만 전자 방법과 후자방법은 state가 변경될 때마다 event handler가 연결되므로 좋지 않은 방법이라고 생각했습니다 ㅠㅠ
이런 이유로 useThrottle을 state와 setState를 사용하는 방식이 아닌 ref를 사용하도록 변경해주었습니다 ! 
systhetic event는 react에서 어떤 추가적인 조치를 …
=> feat: 글 상세 페이지 데스크탑 사이즈 구현 

backend/sokdak/src/main/java/com/wooteco/sokdak/auth/exception/AuthorizationException.java, backend/sokdak/src/main/java/com/wooteco/sokdak/auth/service/AuthService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/member/controller/MemberController.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/acceptance/MemberAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/member/controller/MemberControllerTest.java
지원자로 회원가입 요청 시 서버에러가 남
email이 empty인지 확인했는데 null인지 확인하도록 로직 변경
=> bug: 지원자로 회원가입 안되는 버그 수정

imageserver/sokdakimageserver/build.gradle, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/controller/ImageController.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/domain/Extension.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/domain/Image.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/dto/ImageResponse.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/exception/FileIOException.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/exception/ImageReadException.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/exception/NotSupportedExtensionException.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/service/ImageService.java, imageserver/sokdakimageserver/src/main/java/com/wooteco/sokdak/image/util/ImageCompressor.java, imageserver/sokdakimageserver/src/test/java/com/wooteco/sokdak/image/domain/ExtensionTest.java
- 알파채널 이미지일 경우 압축이 되지 않는 문제 해결
- 이미지가 원치 않게 회전되는 경우에 대한 문제 해결
=> fix: 알파채널 이미지일 경우 압축이 되지 않는 문제 해결

backend/sokdak/src/main/java/com/wooteco/sokdak/aspect/performance/PerformanceAspect.java
쿼리 카운트 AOP에서 DataSource 순환참조 문제 해결
=> fix: 쿼리 카운트 AOP에서 DataSource 순환참조 문제 해결

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/repository/CommentRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/repository/PostRepository.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/repository/CommentRepositoryTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/service/LikeServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/acceptance/PostAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/repository/PostRepositoryTest.java
좋아요 개수 조회 반정규화하여 count 쿼리 제거
native sql을 이용해 update문을 직접 호출하도록 변경했습니다.
=> refactor: 좋아요 개수 조회 반정규화하여 count 쿼리 제거

backend/sokdak/src/main/java/com/wooteco/sokdak/comment/domain/Comment.java, backend/sokdak/src/main/java/com/wooteco/sokdak/comment/service/CommentService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/domain/CommentLike.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/domain/PostLike.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/CommentLikeRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/repository/PostLikeRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/like/service/LikeService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/service/PostService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/comment/domain/CommentTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/like/service/LikeServiceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java
oneToMany에 대해 stream을 돌아 n+1 발생문제 해결
해당 멤버가 좋아요를 눌렀는지 확인하는 과정에서 stream을 돌아 n+1문제 발생하는 부분을 해결했습니다.
=> refactor: oneToMany에 대해 stream을 돌아 n+1 발생문제 해결

backend/sokdak/src/test/java/com/wooteco/sokdak/admin/acceptance/AdminAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/auth/acceptance/AuthAcceptanceTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/util/fixture/HttpMethodFixture.java, backend/sokdak/src/test/resources/application.yml
Nginx에서 프론트에 대한 요청과 백엔드에 대한 요청을 분기하기 위해
request-uri prefix /api로 지정
=> refactor: request-uri prefix /api로 지정

backend/sokdak/src/main/java/com/wooteco/sokdak/admin/dto/PostReportElement.java, backend/sokdak/src/main/java/com/wooteco/sokdak/admin/service/AdminService.java, backend/sokdak/src/main/java/com/wooteco/sokdak/post/domain/Post.java, backend/sokdak/src/main/java/com/wooteco/sokdak/report/domain/PostReport.java, backend/sokdak/src/main/java/com/wooteco/sokdak/report/repository/PostReportRepository.java, backend/sokdak/src/main/java/com/wooteco/sokdak/report/service/PostReportService.java, backend/sokdak/src/test/java/com/wooteco/sokdak/post/domain/PostTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/report/domain/PostReportTest.java, backend/sokdak/src/test/java/com/wooteco/sokdak/report/repository/PostReportRepositoryTest.java
postReport에서 post 다대일 연관관계 간접참조로 리팩터링
post와 postReport를 일대다 단방향으로 변경
도메인 로직 상 생명주기가 달라 post가 먼저 생성되고 postReport가 추가되어 일대다 단방향의 단점인 update쿼리 문제가 발생하지 않음
postReportService의 deleteAllPostReport 메서느 내부 구현 순서를 바꾸면 안됨. post가 연관관계의 주인이라 postReport 컬렉션이 변경되면 변경감지가 일어나 postReportRepository.deleteAllByPostId가 의도대로 동작하지 않음
=> refactor: post와 postReport를 일대다 단방향 관계로 리팩터링
